# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - pdf_data:/var/lib/postgresql/data

volumes:
  pdf_data:
